name:                ttt
version:             0.1.0.0
github:              cohei/TicTacToe
license:             MIT
license-file:        LICENSE
author:              "TANIGUCHI Kohei"
maintainer:          a.d.xvii.kal.mai@gmail.com
copyright:           "2018 TANIGUCHI Kohei"

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis:            Tic Tac Toe AI
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/cohei/fizz-buzz-challenge#readme>

dependencies:
  - base >= 4.9 && < 5
  - MonadRandom
  - directory
  - mtl
  - split
  - time

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: src
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
